### ISSUE TITLE
Change width and height separately

### ISSUE THREAD

**Issue by rupertbayern** [alexlenail/NN-SVG#10]
Hello,

this tool is very neat but I can't use it because my feature maps are not squares. Right now you can adjust the feature map resolution but the feature map is always a square. It would be great if you could change the width and height separately.
Thanks

**Comment by alexlenail** [comment]
@rupertbayern Ooo. What kind of conv are you doing? That sounds fairly non-traditional. 

I would recommend downloading an SVG and editing slightly in inkscape or illustrator, unless you can persuade me this is a really common use case.

**Comment by Raldir** [comment]
It occurs quite frequently in my experience in cases where the domain is not image recognition. Take for example the CNN that has been described by Kim et al., https://arxiv.org/abs/1408.5882. It is neither a requirement nor common practice to use a squared feature map for that kind of CNN. So I think that it would be a nice addition to the great tool you provide.

**Comment by alexlenail** [comment]
Thanks for this feedback, @Raldir. I'll take a look into adding this feature.

**Comment by nvblanco** [comment]
I agree with @Raldir . Non-squared feature maps can be used in a variety of problems, I'd love to see that feature.

**Comment by alexlenail** [comment]
@nvblanco @Raldir @rupertbayern Just so we're clear, are we speaking about the LeNet layout or the AlexNet layout?

**Comment by nvblanco** [comment]
For a journal paper, I find LeNet layout more useful than AlexNet. From my point of view, 2D-diagrams are easier to understand.

**Comment by lukecwalters** [comment]
Hi @zfrenchee, this is a really nice tool, thank you.  But I'm in the same boat as the others on this thread.  Both non-square feature maps and filters shapes are quite common.

**Comment by alexlenail** [comment]
@lw394 are you also in the boat of wanting this primarily for LeNet layouts?

**Comment by lukecwalters** [comment]
I would use it for both.
