### ISSUE TITLE
FCNN layers missing labels 

### ISSUE THREAD

**Issue by eshrh** [alexlenail/NN-SVG#14]
Hey!
I really liked using this tool as a very simple visualization for models, but there might be a bug in the FCNN style.

Adding a extra node at the end of the model leads to a missing Output Layer label. Similarly, adding an extra node after that one leads to both nodes missing their labels. 
![Here's what I mean](https://user-images.githubusercontent.com/16175276/50064102-49ab1780-017d-11e9-901d-96ebc8b1807b.png)

I would have loved to try to PR and solve it myself, but I'm not too comfortable with JS, so I think I'm out of my league a little here!

**Comment by alexlenail** [comment]
Thanks for the bug report, @eshanrh ! I added the labels at the very end so they're liable to have a few bugs. I'll look into it!

**Comment by eshrh** [comment]
That's totally fine, I ended up hiding labels and then adding them myself which wasn't hard at all, but I thought it might be nice to have it working for everyone else!

**Comment by alexlenail** [comment]
@eshanrh would you check for me that this is fixed now (check http://alexlenail.me/NN-SVG/ and make sure to refresh the cache / visit it in incognito)? 

If it isn't fixed, I'd much appreciate some repro steps =)

**Comment by eshrh** [comment]
Works perfectly!
