### ISSUE TITLE
FCNN layer labels remain even after layer is deleted

### ISSUE THREAD

**Issue by eshrh** [alexlenail/NN-SVG#15]
Hello again!

Another thing I found while experimenting a little bit is that layer labels stay on the screen even after the layer is deleted. Using the default model and deleting every layer except the input layer gives this:
![screen shot 2018-12-16 at 9 59 01 pm](https://user-images.githubusercontent.com/16175276/50064214-0604dd80-017e-11e9-982f-45b85dc5e895.png)

**Comment by alexlenail** [comment]
@eshanrh would you check for me that this is fixed now (check http://alexlenail.me/NN-SVG/ and make sure to refresh the cache / visit it in incognito)? 

If it isn't fixed, I'd much appreciate some repro steps =)

**Comment by eshrh** [comment]
Works perfectly!
