### ISSUE TITLE
support line arrow 

### ISSUE THREAD

**Issue by HorsonLiu** [alexlenail/NN-SVG#16]

**Comment by alexlenail** [comment]
@HorsonLiu can you find a picture with nice arrows? My first pass at making arrows isn't that inspiring:

<img width="848" alt="screen shot 2019-02-01 at 5 58 32 pm" src="https://user-images.githubusercontent.com/2761597/52154255-14825800-264b-11e9-8f85-faab97a8d097.png">

**Comment by HorsonLiu** [comment]
what about this?

![default](https://user-images.githubusercontent.com/4844122/52679730-f4b73200-2f70-11e9-9511-e88a0d7b0d20.png)

**Comment by alexlenail** [comment]
<img width="965" alt="screen shot 2019-02-13 at 10 29 30 am" src="https://user-images.githubusercontent.com/2761597/52722763-4ca66680-2f7a-11e9-9e6c-00e7e5ab8e2f.png">

This is included already.
