### ISSUE TITLE
Download SVG button not working on Safari 12.0.2

### ISSUE THREAD

**Issue by captainvera** [alexlenail/NN-SVG#17]
Hey,

I was experimenting around with NN-SVG and I discovered that the 'Download SVG' functionality does not work on safari 12.0.2

It seems to be browser specific as it works as expected on Chrome

**Comment by alexlenail** [comment]
@captainvera thanks for reporting. What kind of error message do you get? Or how does it fail?

**Comment by captainvera** [comment]
On the visual side, nothing happens, it just fails.

But this error pops-up in the JS console: 
![screenshot](https://user-images.githubusercontent.com/5597178/52119254-6d80ca80-2610-11e9-9d2d-072d481d4cfc.png)

Not sure why it only happens on safari (edit: this doesn't show up in chrome, I tested)

**Comment by alexlenail** [comment]
@captainvera I couldn't reproduce this on firefox, chrome, or safari on my machine -- but the error gives a hint that your browsers don't like my google analytics (I wanted to count downloads). 

I've turned off google analytics for the download. Can you see if it works now? 

(perhaps you have an anti-google analytics chrome extension? )

**Comment by captainvera** [comment]
@zfrenchee  It is working correctly now! 

I have Ublock Origin 1.16 installed, maybe it was that? Maybe you could catch the analytics error and continue gracefully if people have an adblocker?
