### ISSUE TITLE
Show dimensions text sprite issue

### ISSUE THREAD

**Issue by aFewThings** [alexlenail/NN-SVG#29]
When I checked `Show Tensor Dimensions` and `Show Conv Dimensions` in AlexNet style, the text sprite (width and height) is showing wrong place. The width and height texts seem to be exchanged each other in location. 

![issue](https://user-images.githubusercontent.com/16372530/69615629-916a3c80-1078-11ea-8a4e-6e0386007c0b.JPG)

**Comment by alexlenail** [comment]
Thanks for the issue. Can you check that #30 fixes this?

**Comment by aFewThings** [comment]
I commented your #30 :)
