### ISSUE TITLE
Unicode characters not supported

### ISSUE THREAD

**Issue by Pavo98** [alexlenail/NN-SVG#34]
Can you add support for unicode characters in layer description?
Right now it raises following error when "Download SVG" is clicked:
> LeNet.html:371 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
>     at HTMLAnchorElement.<anonymous> (http://alexlenail.me/NN-SVG/LeNet.html:371:63)
>    at HTMLAnchorElement.<anonymous> (https://d3js.org/d3.v5.min.js:2:10935)

I found [this](https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte) solution online: `btoa(unescape(encodeURIComponent(str)))`

**Comment by alexlenail** [comment]
Hi @Pavo98. In fact, that's what I have in the code: 

https://github.com/alexlenail/NN-SVG/blob/f99ca4363f9b71398ce7504d72314244dddde43e/index.html#L357

Someone had this issue before, and it had to do with an extension they had on their browser. Could you please reproduce on a few browsers, and if so, please send me the string which you can't download?

**Comment by Pavo98** [comment]
That is fixed just for FCN in file index.html. In LeNet.html it doesn't have that:
https://github.com/alexlenail/NN-SVG/blob/f99ca4363f9b71398ce7504d72314244dddde43e/LeNet.html#L371

I have issues in Chrome 83.0 and Firefox 77.0 both are 64-bit.
Problematic string is "Sloj sažimanja" where "ž" is the problem.

**Comment by alexlenail** [comment]
Thanks for reporting, @Pavo98. Please verify your issue is fixed.

**Comment by Pavo98** [comment]
It is fixed.
Thanks @alexlenail.
