### ISSUE TITLE
feature request: "Fully-Connected graph groups mode"

### ISSUE THREAD

**Issue by koke2c95** [alexlenail/NN-SVG#36]
Thank you great work!
Fully-Connected groups connection support

**Comment by alexlenail** [comment]
Could you link to a figure which shows what you mean? 
Thanks :)

**Comment by koke2c95** [comment]
> Could you link to a figure which shows what you mean?
> Thanks :)

 like this
![image](https://user-images.githubusercontent.com/26929386/96582466-e86ea500-130d-11eb-81d6-4ac1dfe82e11.png)
[conv channel groups  = 1](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html)

**Comment by alexlenail** [comment]
This seems like a figure you could make using the fully-connected style. 

The pytorch conv2D docs you linked to describe a vanilla 2D conv I think, which was first visually described using the LeNet architecture.

**Comment by koke2c95** [comment]
> This seems like a figure you could make using the fully-connected style.
> 
> The pytorch conv2D docs you linked to describe a vanilla 2D conv I think, which was first visually described using the LeNet architecture.

@alexlenail 
sorry, not that meaning
 that 2D conv is a groups fig example, not LeNet architecture style.
![image](https://user-images.githubusercontent.com/26929386/96584493-e22df800-1310-11eb-8765-b7c83e2b7de0.png)

if no groups mode support
i can't make these green line (1 to 1)
![image](https://user-images.githubusercontent.com/26929386/96583882-fc1b0b00-130f-11eb-9b7f-ee5fb2319f5c.png)
