### ISSUE TITLE
How to create jpeg(300+ dpi)/png publication quality images from NN-SVG

### ISSUE THREAD

**Issue by revanks** [alexlenail/NN-SVG#37]
Hi Alex,

I am using NN-SVG tool: http://alexlenail.me/NN-SVG/index.html

I need high-quality images of a fully connected NN figure either in png/jpg. Could you please instruct me how do I use it?

Thanks
Sachin

**Comment by alexlenail** [comment]
I would recommend taking a screenshot.

**Comment by revanks** [comment]
Ok alright, thanks.
