### ISSUE TITLE
Link to Underscore.js is broken

### ISSUE THREAD

**Issue by ghost** [alexlenail/NN-SVG#40]
Hello! 

Alexnet and Lenet isn´t working in demo and repo because <script type="text/javascript" src="https://underscorejs.org/underscore-min.js"></script> is not available.

For solving this issue just replace it for:

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/underscore@1.13.0/underscore-umd-min.js"></script>

**Comment by alexlenail** [comment]
Thanks @betances !

https://github.com/alexlenail/NN-SVG/commit/d8ff4019054f72fdfd211aa86e1bcbdcd9943d14
