### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by eleezs** [alexlenail/NN-SVG#41]
This is really a great work.
but I must say a little tutorial or write explaining what the parameters mean could really help a newbie?
thanks

**Comment by alexlenail** [comment]
If you're looking for a tutorial on how to use this library on your own site, there's one on the wiki: https://github.com/alexlenail/NN-SVG/wiki

If you're looking for a tutorial on Neural Networks generally, I think that's out of scope for this repository, but if you find one that helps you please let me know and I'll link to it!
