### ISSUE TITLE
Multiple outputs?

### ISSUE THREAD

**Issue by Ademord** [alexlenail/NN-SVG#43]
I am trying to draw the PPO network and I can't seem to be able to draw to output heads with the AlexNet style.

**Comment by alexlenail** [comment]
What is the PPO network supposed to look like?

**Comment by Ademord** [comment]
Hello, it looks something like this
![image](https://user-images.githubusercontent.com/4501464/131903312-747a6e5d-ea81-4669-844b-67bfc457d07d.png)
I dont know how this image was done


Additionally.. the possibility to set two separate inputs would be AMAZING (with labels to specify what is what)

Let me upload another photo to show another variant with a different diagram I had to somehow work around...

![image](https://user-images.githubusercontent.com/4501464/131903564-5d962b8e-d1f4-4f92-9c43-545000e285fe.png)

**Comment by alexlenail** [comment]
Hi @Ademord, 
The goal of this repo, as I see it, is primarily to automate the N^2 operation of drawing edges between nodes in an FCNN -- big waste of your and my time. Adding individual inputs/outputs, as in both the figures I see above, would take us some time to code, but it strikes me as probably pretty quick to add them by hand. Does that make sense? 

You're welcome to fork/open a PR adding this functionality, but I won't have time for it. :(

**Comment by Ademord** [comment]
Thanks so much for the clarification 👍🏻
