### ISSUE TITLE
Feature Request: Models with Branches

### ISSUE THREAD

**Issue by harshraj22** [alexlenail/NN-SVG#47]
Thank you for the great website.

Models with branches have become very common these days. Having a feature to draw them as well would be great.
Examples include [Siamese Network](https://miro.medium.com/max/1400/1*0E9104t29iMBmtvq7G1G6Q.png), Most [Multi Modal Models](https://miro.medium.com/max/1200/1*8ROay1Yjc42UMjnBurYRrw.png) and so on

**Comment by alexlenail** [comment]
Thanks for these suggestions, @harshraj22! I agree there are many architectures one could aim to make diagrams for, but I don't think I can keep up with the pace of innovation in the NN field. If you make one of these I'm happy to link to it!
