### ISSUE TITLE
Not an issue, but a suggestion/query

### ISSUE THREAD

**Issue by massisenergy** [alexlenail/NN-SVG#55]
This is a very useful app, especially with the `.svg` download option 👍🏽

My question is - is there any plan to include more complicated Deep Learning algorithmic structures such as the *[Transformers](https://en.wikipedia.org/wiki/Transformer_(machine_learning_model))* (such as BERT, ViT, etc.)?

**Comment by alexlenail** [comment]
Hi @massisenergy 
What kind of diagram would you want to represent a transformer?

**Comment by lhallee** [comment]
I second this question. The field sorely needs automatic structuring of transformer like diagrams, especially with the introduction of MOE and state space models.
![image](https://github.com/alexlenail/NN-SVG/assets/72926928/2f11b7ae-7107-4f67-8202-ad2a6825ff29)
How to do this effectively? Not sure. Some cross between the AlexNet style and AlphaFold style would be really interesting.
![image](https://github.com/alexlenail/NN-SVG/assets/72926928/6e4b2f19-d6fa-45de-9f40-8dc3f7022da5)

**Comment by alexlenail** [comment]
Is there a sort of graphic that is tedious to make with powerpoint to represent transformers (similar to all the lines in an FCNN)? 

Another important question is: is a lightweight web tool better for making these than a hypothetical python utility which parses your code to generate a diagram?

**Comment by lhallee** [comment]
Parsing to code to generate a diagram would be much better! For example, orienting all the layers correctly from a print of a Pytorch model or something.

**Comment by alexlenail** [comment]
Agreed -- I think there should be a python utility you download to your machine to parse your code -- it's out of scope for a web tool like NN-SVG. I'd love to see a "pytorch-SVG" utility!
