### ISSUE TITLE
AlexNet SVG Renderer Issue

### ISSUE THREAD

**Issue by NeonBeach** [alexlenail/NN-SVG#65]
when switching to the svg renderer from webgl renderer, text sprites appear white or are not visible, although the option is disabled and false.
![nn_issue](https://github.com/user-attachments/assets/1cf2a7ea-8884-499f-88a2-c517401a284a)

**Comment by alexlenail** [comment]
I see that as well. That's a shame, it used to work. Browsers must have changed.
