### ISSUE TITLE
Download Issue for AlexNet Style SVG

### ISSUE THREAD

**Issue by ynngliu** [alexlenail/NN-SVG#9]
Hello. First thank you for the great work. I found this tool to be very handy and well-made. However, I do find an issue when trying to download the SVG file for AlexNet style schematics. The downloaded files seem to be empty. Could you take a look? Thanks!

**Comment by alexlenail** [comment]
@ynngliu thanks for reporting this! I'm seeing this issue as well. That's strange.. it was working a little while ago...

**Comment by alexlenail** [comment]
@ynngliu fixed. Thanks for reporting!

**Comment by ynngliu** [comment]
Thanks!
